#!/usr/bin/perl


# This script removes duplicated entries from qt-koo.pot after
# it's been generated by lconvert. gettext doesn't allow duplicated
# entries and importing the file to launchpad doesn't work.

use Locale::PO;

$href = Locale::PO->load_file_ashash('Koo/l10n/qt-koo.pot');
Locale::PO->save_file_fromhash('Koo/l10n/qt-koo.pot',$href);
